# Generated by Django 4.2.2 on 2023-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('gen-phy', 'General Physician'), ('derma', 'Dermatology'), ('dentist', 'Dentistry')], default='gen-phy', max_length=20),
        ),
    ]
