# Generated by Django 4.2.2 on 2023-06-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
