# Generated by Django 4.2.2 on 2023-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
