# Generated by Django 4.2.2 on 2023-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('gen-phy', 'General Physician'), ('derma', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('dentist', 'Dentistry'), ('gynecology', 'Gynecology'), ('ophthalmology', 'Ophthalmology'), ('neurology', 'Neurology'), ('psychology', 'Psychology'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('gastroenterology', 'Gastroenterology'), ('ent', 'ENT')], default='gen-phy', max_length=20),
        ),
    ]
