# Generated by Django 4.2.2 on 2023-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_doctor_consultation_fee_doctor_consultation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
