# Generated by Django 4.2.2 on 2023-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_consultation_time_doctor_consultation_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('gen-phy', 'General Physician'), ('derma', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('dentist', 'Dentistry'), ('gynecology', 'Gynecology'), ('ophthalmology', 'Ophthalmology'), ('neurology', 'Neurology'), ('psychology', 'Psychology'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('gastroenterology', 'Gastroenterology'), ('ent', 'ENT')], default='', max_length=20),
        ),
    ]
