# Generated by Django 4.2.2 on 2023-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctor_dislike_count_doctor_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dislike_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='like_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
