# Generated by Django 4.2.2 on 2023-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
